# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86b41898676631667fe6d18b948f515b66226fe0944a78f9acec2fdc36250903c4727eb1ffb6a3adf6ad7903992840ecfee9a31c8a092024d572fb7dcb006b51

test:
  secret_key_base: 32f0a58e0e329e24b0b309cd0929eb89a3b17d300b607adb1b093b1c801a1759e46da9ff96390569a5984a286b6cbb9b7bc4c6b98abb6eda3889557962acf639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
